[package]
name = "treecoin"
version = "0.1.0"
authors = ["RobinLinus <robinlinus@users.noreply.github.com>"]

[dependencies]
rand = "0.5.2"
blake2-rfc = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
